key_mapped = {
'a':'hid_write(NULL_CHAR*2 +chr(4)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'b':'hid_write(NULL_CHAR*2 +chr(5)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'c':'hid_write(NULL_CHAR*2 +chr(6)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'd':'hid_write(NULL_CHAR*2 +chr(7)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'e':'hid_write(NULL_CHAR*2 +chr(8)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'f':'hid_write(NULL_CHAR*2 +chr(9)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'g':'hid_write(NULL_CHAR*2 +chr(10)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'h':'hid_write(NULL_CHAR*2 +chr(11)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'i':'hid_write(NULL_CHAR*2 +chr(12)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'j':'hid_write(NULL_CHAR*2 +chr(13)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'k':'hid_write(NULL_CHAR*2 +chr(14)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'l':'hid_write(NULL_CHAR*2 +chr(15)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'm':'hid_write(NULL_CHAR*2 +chr(16)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'n':'hid_write(NULL_CHAR*2 +chr(17)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'o':'hid_write(NULL_CHAR*2 +chr(18)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'p':'hid_write(NULL_CHAR*2 +chr(19)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'q':'hid_write(NULL_CHAR*2 +chr(20)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'r':'hid_write(NULL_CHAR*2 +chr(21)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
's':'hid_write(NULL_CHAR*2 +chr(22)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
't':'hid_write(NULL_CHAR*2 +chr(23)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'u':'hid_write(NULL_CHAR*2 +chr(24)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'v':'hid_write(NULL_CHAR*2 +chr(25)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'w':'hid_write(NULL_CHAR*2 +chr(26)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'x':'hid_write(NULL_CHAR*2 +chr(27)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'y':'hid_write(NULL_CHAR*2 +chr(28)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'z':'hid_write(NULL_CHAR*2 +chr(29)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'A':'hid_write(chr(2)+NULL_CHAR+chr(4)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'B':'hid_write(chr(2)+NULL_CHAR+chr(5)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'C':'hid_write(chr(2)+NULL_CHAR+chr(6)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'D':'hid_write(chr(2)+NULL_CHAR+chr(7)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'E':'hid_write(chr(2)+NULL_CHAR+chr(8)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'F':'hid_write(chr(2)+NULL_CHAR+chr(9)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'G':'hid_write(chr(2)+NULL_CHAR+chr(10)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'H':'hid_write(chr(2)+NULL_CHAR+chr(11)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'I':'hid_write(chr(2)+NULL_CHAR+chr(12)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'J':'hid_write(chr(2)+NULL_CHAR+chr(13)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'K':'hid_write(chr(2)+NULL_CHAR+chr(14)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'L':'hid_write(chr(2)+NULL_CHAR+chr(15)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'M':'hid_write(chr(2)+NULL_CHAR+chr(16)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'N':'hid_write(chr(2)+NULL_CHAR+chr(17)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'O':'hid_write(chr(2)+NULL_CHAR+chr(18)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'P':'hid_write(chr(2)+NULL_CHAR+chr(19)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'Q':'hid_write(chr(2)+NULL_CHAR+chr(20)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'R':'hid_write(chr(2)+NULL_CHAR+chr(21)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'S':'hid_write(chr(2)+NULL_CHAR+chr(22)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'T':'hid_write(chr(2)+NULL_CHAR+chr(23)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'U':'hid_write(chr(2)+NULL_CHAR+chr(24)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'V':'hid_write(chr(2)+NULL_CHAR+chr(25)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'W':'hid_write(chr(2)+NULL_CHAR+chr(26)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'X':'hid_write(chr(2)+NULL_CHAR+chr(27)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'Y':'hid_write(chr(2)+NULL_CHAR+chr(28)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'Z':'hid_write(chr(2)+NULL_CHAR+chr(29)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'1':'hid_write(NULL_CHAR*2 +chr(30)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'2':'hid_write(NULL_CHAR*2 +chr(31)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'3':'hid_write(NULL_CHAR*2 +chr(32)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'4':'hid_write(NULL_CHAR*2 +chr(33)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'5':'hid_write(NULL_CHAR*2 +chr(34)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'6':'hid_write(NULL_CHAR*2 +chr(35)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'7':'hid_write(NULL_CHAR*2 +chr(36)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'8':'hid_write(NULL_CHAR*2 +chr(37)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'9':'hid_write(NULL_CHAR*2 +chr(38)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'0':'hid_write(NULL_CHAR*2 +chr(39)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'!':'hid_write(chr(2)+NULL_CHAR+chr(30)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'@':'hid_write(chr(2)+NULL_CHAR+chr(31)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'#':'hid_write(chr(2)+NULL_CHAR+chr(32)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'&':'hid_write(chr(2)+NULL_CHAR+chr(36)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'*':'hid_write(chr(2)+NULL_CHAR+chr(37)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'(':'hid_write(chr(2)+NULL_CHAR+chr(38)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
')':'hid_write(chr(2)+NULL_CHAR+chr(39)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'-':'hid_write(NULL_CHAR*2 +chr(45)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'=':'hid_write(NULL_CHAR*2 +chr(46)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'{':'hid_write(NULL_CHAR*2 +chr(47)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'}':'hid_write(NULL_CHAR*2 +chr(48)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'\\':'hid_write(NULL_CHAR*2 +chr(49)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
';':'hid_write(NULL_CHAR*2 +chr(51)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'':'hid_write(NULL_CHAR*2 +chr(52)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'`':'hid_write(NULL_CHAR*2 +chr(53)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
',':'hid_write(NULL_CHAR*2 +chr(54)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'.':'hid_write(NULL_CHAR*2 +chr(55)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'/':'hid_write(NULL_CHAR*2 +chr(56)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'0':'hid_write(chr(2)+NULL_CHAR+chr(50)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
':':'hid_write(chr(2)+NULL_CHAR+chr(51)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'"':'hid_write(chr(2)+NULL_CHAR+chr(52)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'<':'hid_write(chr(2)+NULL_CHAR+chr(54)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'>':'hid_write(chr(2)+NULL_CHAR+chr(55)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'?':'hid_write(chr(2)+NULL_CHAR+chr(56)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'}':'hid_write(NULL_CHAR*2 +chr(79)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'{':'hid_write(NULL_CHAR*2 +chr(80)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
']':'hid_write(chr(2)+NULL_CHAR+chr(79)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',
'[':'hid_write(chr(2)+NULL_CHAR+chr(80)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)',

#Next Signs are used for different keymappings - change if you want to
'$':'hid_write(NULL_CHAR*2 +chr(40)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #ENTER
'%':'hid_write(NULL_CHAR*2 +chr(41)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #ESC
'^':'hid_write(NULL_CHAR*2 +chr(42)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #BACKSPACE
'~':'hid_write(NULL_CHAR*2 +chr(43)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #TAB
'_':'hid_write(NULL_CHAR*2 +chr(44)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #SPATIE
'+':'hid_write(NULL_CHAR*2 +chr(70)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #PRINT SCREEN
'[':'hid_write(NULL_CHAR*2 +chr(76)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #DELETE
']':'hid_write(chr(5)+NULL_CHAR+chr(76)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #CTRL+ALT+DEL
'|':'hid_write(NULL_CHAR*2 +chr(81)+NULL_CHAR*5)\nhid_write(NULL_CHAR * 8)', #DOWN
}
